"use client";

import * as React from "react";
import { Box, Check, ChevronDown, Circle, Clock3, Download, FlaskConical, GitBranch, GitCommitHorizontal, List, LoaderCircle, Package, Play, Rocket, Square, X, Scale, RotateCcw, Sparkles, ShieldCheck } from "lucide-react";

export type StageStatus = "queued" | "running" | "passed" | "failed" | "skipped" | "canceled";
export interface PipelineLog { time: string; message: string; level?: "info" | "warning" | "error" }
export interface PipelineStage { id: string; name: string; kind?: "checkout" | "build" | "test" | "deploy" | "receiving" | "prep" | "pack" | "returns" | "recovery"; status: StageStatus; durationMs?: number; logs: PipelineLog[] }
export interface PipelineRun { id: string; branch: string; commit: string; startedAt: string; stages: PipelineStage[] }
export interface BuildPipelineProps {
  runs: PipelineRun[];
  title?: string;
  subtitle?: string;
  selectedRunId?: string;
  onRunChange?: (run: PipelineRun) => void;
  onStageSelect?: (stage: PipelineStage, run: PipelineRun) => void;
  onRerun?: (run: PipelineRun) => void;
  onCancel?: (run: PipelineRun) => void;
  busyRunId?: string | null;
  rerunLabel?: string;
  defaultView?: "pipeline" | "list";
  theme?: "auto" | "light" | "dark";
  className?: string;
  style?: React.CSSProperties;
}

const statusLabel: Record<StageStatus, string> = { queued: "Queued", running: "Running", passed: "Passed", failed: "Failed", skipped: "Skipped", canceled: "Canceled" };
const stageIcon = (kind?: string) => {
  if (kind === "receiving") return Package;
  if (kind === "prep") return Sparkles;
  if (kind === "pack") return Box;
  if (kind === "returns") return RotateCcw;
  if (kind === "recovery") return Scale;
  if (kind === "checkout") return GitCommitHorizontal;
  if (kind === "test") return FlaskConical;
  if (kind === "deploy") return Rocket;
  return Package;
};
const statusIcon = (status: StageStatus) => status === "passed" ? Check : status === "failed" || status === "canceled" ? X : status === "running" ? LoaderCircle : Circle;
const duration = (ms: number) => ms >= 60_000 ? `${Math.floor(ms / 60_000)}m ${Math.floor(ms % 60_000 / 1000)}s` : `${(Math.max(0, ms) / 1000).toLocaleString("en-US", { maximumFractionDigits: 1 })}s`;
const runStatus = (stages: PipelineStage[]): StageStatus => stages.some(stage => stage.status === "failed") ? "failed" : stages.some(stage => stage.status === "canceled") ? "canceled" : stages.some(stage => stage.status === "running") ? "running" : stages.some(stage => stage.status === "queued") || !stages.length ? "queued" : stages.every(stage => stage.status === "skipped") ? "skipped" : "passed";
const points = (vertices: number[][]) => vertices.map(point => point.map(value => value.toFixed(2)).join(",")).join(" ");

function stations(count: number, width: number) {
  const columns = Math.max(1, Math.min(count, Math.floor((width - 16) / 120))), rows = Math.ceil(count / columns);
  return { height: Math.max(142, rows * 128 + 14), nodes: Array.from({ length: count }, (_, index) => {
    const row = Math.floor(index / columns), column = row % 2 ? columns - 1 - index % columns : index % columns;
    const x = (column + .5) * width / columns, y = 72 + row * 128;
    const base = [[x, y - 18], [x + 28, y - 4], [x, y + 10], [x - 28, y - 4]], roof = base.map(([px, py]) => [px, py - 24]);
    return { x, y, base, roof };
  }) };
}

/** Controlled deployment history. Actions are callbacks; the component never starts remote jobs. */
export function BuildPipeline({ runs, title = "Commerce Verification Pipeline", subtitle = "From inbound receiving to channel loss recovery.", selectedRunId, onRunChange, onStageSelect, onRerun, onCancel, busyRunId, rerunLabel = "Run again", defaultView = "pipeline", theme = "auto", className = "", style }: BuildPipelineProps) {
  const [localRun, setLocalRun] = React.useState(selectedRunId ?? runs[0]?.id);
  const [selectedStage, setSelectedStage] = React.useState<string | null>(null);
  const [view, setView] = React.useState(defaultView);
  const [width, setWidth] = React.useState(640);
  const [logFilter, setLogFilter] = React.useState("all");
  const plotRef = React.useRef<HTMLDivElement>(null);
  const id = React.useId();

  React.useEffect(() => {
    if (selectedRunId) setLocalRun(selectedRunId);
    else if (!runs.some(r => r.id === localRun) && runs[0]) setLocalRun(runs[0].id);
  }, [selectedRunId, runs, localRun]);

  const run = runs.find(item => item.id === (selectedRunId ?? localRun)) ?? runs[0];
  const stages = run?.stages ?? [];
  const selected = stages.find(stage => stage.id === selectedStage) ?? stages.find(stage => stage.status === "failed" || stage.status === "running") ?? stages[0];
  const status = runStatus(stages), elapsed = stages.reduce((sum, stage) => sum + Math.max(0, stage.durationMs ?? 0), 0), passed = stages.filter(stage => stage.status === "passed").length;
  const scene = React.useMemo(() => stations(stages.length, width), [stages.length, width]);
  const logs = selected?.logs.filter(log => logFilter === "all" || log.level === "error" || log.level === "warning") ?? [];
  React.useEffect(() => { const element = plotRef.current; if (!element) return; const observer = new ResizeObserver(() => setWidth(Math.max(240, element.getBoundingClientRect().width))); observer.observe(element); return () => observer.disconnect(); }, [view, run?.id, stages.length]);
  const chooseStage = (stage: PipelineStage) => { setSelectedStage(stage.id); setLogFilter("all"); if (run) onStageSelect?.(stage, run); };
  const changeRun = (runId: string) => { const next = runs.find(item => item.id === runId); if (!next) return; setLocalRun(runId); setSelectedStage(null); setLogFilter("all"); onRunChange?.(next); };
  const exportLog = () => { if (!run || !selected) return; const blob = new Blob([selected.logs.map(log => `[${log.time}] ${(log.level ?? "info").toUpperCase()} ${log.message}`).join("\n")], { type: "text/plain;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${run.id}-${selected.id}.log`; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); };

  return <section className={`build-pipeline ${className}`} data-theme={theme} style={style} aria-label={title}>
    <style>{styles}</style>
    <header className="bp-header"><div className="bp-heading"><span className="bp-emblem"><ShieldCheck size={19} strokeWidth={2.2} aria-hidden="true" /></span><div><h2>{title}</h2><p>{subtitle}</p></div></div><div className="bp-header-tools"><label className="bp-run-select"><span className="bp-sr-only">Choose pipeline run</span><select value={run?.id ?? ""} disabled={!runs.length} onChange={event => changeRun(event.target.value)}>{runs.length ? runs.map(item => <option key={item.id} value={item.id}>#{item.id} · {item.branch}</option>) : <option value="">No runs</option>}</select><ChevronDown size={12} aria-hidden="true" /></label><div className="bp-switch" role="group" aria-label="Pipeline view"><button type="button" aria-pressed={view === "pipeline"} onClick={() => setView("pipeline")}><Box size={14} aria-hidden="true" /><span>3D</span></button><button type="button" aria-pressed={view === "list"} onClick={() => setView("list")}><List size={14} aria-hidden="true" /><span>List</span></button></div></div></header>
    {!run ? <div className="bp-empty"><GitBranch size={26} strokeWidth={1.4} aria-hidden="true" /><strong>No runs yet</strong><p>Your build stages will appear here when supplied.</p></div> : <>
      <div className="bp-stats"><div><span>Run status</span><strong className="bp-status-value" data-status={status} aria-live="polite">{statusLabel[status]}</strong><small>#{run.id}</small></div><div><span>Total duration</span><strong>{duration(elapsed)}</strong><small>sum of stage durations</small></div><div><span>Stages passed</span><strong>{passed}<em> / {stages.length}</em></strong><small>in this pipeline</small></div></div>
      <div className="bp-context"><span><GitBranch size={12} aria-hidden="true" />{run.branch}<span className="bp-dot">·</span><code>{run.commit.slice(0, 7)}</code></span><div>{status === "running" && onCancel && <button className="bp-cancel" type="button" onClick={() => onCancel(run)}><Square size={11} aria-hidden="true" />Cancel</button>}{onRerun && <button type="button" className="bp-replay" disabled={Boolean(busyRunId)} onClick={() => onRerun(run)}><Play size={11} aria-hidden="true" />{busyRunId === run.id ? "Replaying…" : rerunLabel}</button>}</div></div>
      {!stages.length ? <div className="bp-empty"><strong>No stages supplied</strong><p>This run has not received any stage records.</p></div> : view === "pipeline" ? <div className="bp-plot" ref={plotRef} style={{ height: scene.height }}>
        <svg className="bp-chart" width="100%" height={scene.height} viewBox={`0 0 ${width} ${scene.height}`} role="img" aria-labelledby={`${id}-title ${id}-desc`}><title id={`${id}-title`}>Build stages in execution order</title><desc id={`${id}-desc`}>{stages.map(stage => `${stage.name}: ${statusLabel[stage.status]}`).join(". ")}. Use the labeled station buttons to inspect logs.</desc><defs><marker id={`${id}-arrow`} markerWidth={5} markerHeight={5} refX={4} refY={2.5} orient="auto"><path d="M0,0 L5,2.5 L0,5 Z" fill="var(--bp-line)" /></marker></defs>{scene.nodes.slice(0, -1).map((node, index) => { const next = scene.nodes[index + 1], direction = next.x > node.x ? 1 : -1; const d = next.y === node.y ? `M${node.x + direction * 34},${node.y - 28} L${next.x - direction * 35},${next.y - 28}` : `M${node.x + (node.x > width / 2 ? 34 : -34)},${node.y - 28} H${node.x + (node.x > width / 2 ? 53 : -53)} V${next.y - 28} H${next.x + (node.x > width / 2 ? 35 : -35)}`; return <path key={index} d={d} fill="none" stroke="var(--bp-line)" strokeWidth={1.2} strokeDasharray={stages[index].status === "passed" ? undefined : "3 4"} markerEnd={`url(#${id}-arrow)`} />; })}{scene.nodes.map((node, index) => <g key={stages[index].id} className="bp-station-block" style={{ transform: selected?.id === stages[index].id ? "translateY(-5px)" : "none", transition: "transform 0.2s ease, filter 0.2s ease", filter: selected?.id === stages[index].id ? "brightness(1.15) drop-shadow(0px 8px 10px rgba(0,0,0,0.2))" : "none" }} data-status={stages[index].status}><polygon points={points(node.base.map(([x, y]) => [x, y + 5]))} fill="var(--bp-ground)" /><polygon className="bp-left" points={points([node.roof[3], node.roof[2], node.base[2], node.base[3]])} /><polygon className="bp-right" points={points([node.roof[1], node.roof[2], node.base[2], node.base[1]])} /><polygon className="bp-roof" points={points(node.roof)} /></g>)}</svg>
        {scene.nodes.map((node, index) => { const stage = stages[index], Icon = stageIcon(stage.kind), StatusIcon = statusIcon(stage.status); return <button type="button" className="bp-station-button" key={stage.id} data-stage={stage.id} data-status={stage.status} aria-pressed={selected?.id === stage.id} aria-label={`${stage.name}, ${statusLabel[stage.status]}, ${duration(stage.durationMs ?? 0)}. Inspect logs.`} style={{ left: node.x - 54, top: node.y - 46 }} onClick={() => chooseStage(stage)}><span className="bp-station-icon"><Icon size={17} strokeWidth={1.6} aria-hidden="true" /></span><strong>{stage.name}</strong><span className="bp-station-state"><StatusIcon size={10} aria-hidden="true" />{statusLabel[stage.status]}<span className="bp-station-duration">{stage.durationMs ? duration(stage.durationMs) : ""}</span></span></button>; })}
      </div> : <div className="bp-list">{stages.map(stage => { const Icon = stageIcon(stage.kind), StatusIcon = statusIcon(stage.status); return <button className="bp-list-row" type="button" key={stage.id} data-stage={stage.id} data-status={stage.status} aria-pressed={selected?.id === stage.id} onClick={() => chooseStage(stage)}><Icon size={16} aria-hidden="true" /><span><strong>{stage.name}</strong><small>{stage.logs.length} log entries</small></span><span className="bp-list-status"><StatusIcon size={12} aria-hidden="true" />{statusLabel[stage.status]}</span><span className="bp-list-duration">{duration(stage.durationMs ?? 0)}</span></button>; })}</div>}
      {selected && <div className="bp-log-panel"><div className="bp-log-header"><div><strong>{selected.name}</strong><span className="bp-stage-badge" data-status={selected.status}>{statusLabel[selected.status]}</span></div><div><label className="bp-log-filter"><span className="bp-sr-only">Filter stage logs</span><select value={logFilter} onChange={event => setLogFilter(event.target.value)}><option value="all">All logs</option><option value="issues">Warnings & errors</option></select><ChevronDown size={11} aria-hidden="true" /></label><button type="button" className="bp-export" onClick={exportLog} aria-label="Download selected stage log" disabled={!selected.logs.length}><Download size={13} aria-hidden="true" /></button></div></div><div className="bp-log-lines" aria-label={`${selected.name} logs`}>{logs.length ? logs.slice(-4).map((log, index) => <div className="bp-log-line" key={`${log.time}-${index}`} data-level={log.level ?? "info"}><time>{log.time}</time><code>{log.message}</code></div>) : <p className="bp-no-logs">{logFilter === "issues" ? "No warnings or errors in this stage." : selected.status === "queued" ? "Waiting for the previous stage." : "No log entries yet."}</p>}</div>{logs.length > 4 && <details className="bp-full-logs" key={`${run.id}-${selected.id}-${logFilter}`}><summary>Earlier log entries ({logs.length - 4})<ChevronDown size={12} aria-hidden="true" /></summary>{logs.slice(0, -4).map((log, index) => <div className="bp-log-line" key={index} data-level={log.level ?? "info"}><time>{log.time}</time><code>{log.message}</code></div>)}</details>}</div>}
      <footer className="bp-footer"><span><Clock3 size={12} aria-hidden="true" />Started {Number.isNaN(new Date(run.startedAt).getTime()) ? "at an unspecified time" : new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit", timeZone: "UTC" }).format(new Date(run.startedAt))} UTC</span><span>{stages.length} stages</span></footer>
    </>}
  </section>;
}

export default BuildPipeline;

const styles = `
.build-pipeline{--bp-surface:rgba(255, 255, 255, 0.78);--bp-ink:#171717;--bp-muted:#64748b;--bp-border:rgba(226, 232, 240, 0.8);--bp-hover:rgba(241, 245, 249, 0.85);--bp-subtle:rgba(248, 250, 252, 0.7);--bp-selected:#1e293b;--bp-on-selected:#ffffff;--bp-ground:rgba(241, 244, 242, 0.6);--bp-line:#94a3b8;--bp-green:#16a34a;--bp-green-fill:#bbf7d0;--bp-blue:#2563eb;--bp-blue-fill:#bfdbfe;--bp-red:#dc2626;--bp-red-fill:#fecaca;--bp-gray-fill:#e2e8f0;--bp-shadow:rgba(15, 23, 42, 0.08);color:var(--bp-ink);background:var(--bp-surface);backdrop-filter:blur(16px);-webkit-backdrop-filter:blur(16px);border:1px solid var(--bp-border);border-radius:24px;box-shadow:0 8px 32px 0 var(--bp-shadow), inset 0 0 0 1px rgba(255,255,255,0.6);width:100%;max-width:880px;margin-inline:auto;overflow:hidden;font-family:Inter,Geist,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;font-size:13px;line-height:1.5;text-align:left;box-sizing:border-box;isolation:isolate}
.build-pipeline *{box-sizing:border-box}.build-pipeline button,.build-pipeline select{font:inherit;color:inherit}.build-pipeline button{cursor:pointer;transition:background .16s ease,color .16s ease,transform .16s ease}.build-pipeline button:active:not(:disabled){transform:translateY(1px)}.build-pipeline button:disabled{opacity:.45;cursor:default}.build-pipeline svg:not(.bp-chart){flex:none}.bp-sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}
.bp-header{display:flex;align-items:center;justify-content:space-between;gap:14px;padding:24px 28px 0}.bp-heading{display:flex;gap:12px;align-items:center;min-width:0}.bp-emblem{width:38px;height:38px;border:1px solid var(--bp-border);border-radius:12px;display:grid;place-items:center;background:rgba(255,255,255,0.85);box-shadow:0 2px 6px rgba(0,0,0,0.04);flex:none;color:#773C30}.bp-heading h2{font-size:16px;font-weight:700;letter-spacing:-.3px;line-height:1.3;margin:0;color:#0f172a}.bp-heading p{font-size:12px;line-height:1.4;color:var(--bp-muted);margin:3px 0 0}.bp-header-tools{display:flex;align-items:center;gap:10px;min-width:0}.bp-run-select{position:relative;display:flex;align-items:center;min-width:0}.bp-run-select select{appearance:none;background:rgba(255,255,255,0.9);border:1px solid var(--bp-border);border-radius:10px;height:34px;padding:0 28px 0 11px;font-size:12px;font-weight:600;max-width:180px;min-width:0;text-overflow:ellipsis;box-shadow:0 1px 3px rgba(0,0,0,0.03)}.bp-run-select>svg{position:absolute;right:10px;pointer-events:none;color:var(--bp-muted)}.bp-switch{display:flex;padding:3px;background:rgba(241,245,249,0.7);border:1px solid var(--bp-border);border-radius:10px;gap:3px;flex:none}.bp-switch button{display:flex;align-items:center;justify-content:center;gap:5px;border:0;background:transparent;border-radius:7px;height:28px;padding:0 10px;font-size:12px;font-weight:600;color:var(--bp-muted)}.bp-switch button:hover{background:rgba(255,255,255,0.8);color:var(--bp-ink)}.bp-switch button[aria-pressed=true],.bp-switch button[aria-pressed=true]:hover{background:#0f172a;color:#ffffff;box-shadow:0 2px 6px rgba(0,0,0,0.1)}
.bp-stats{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin:26px 28px 20px}.bp-stats>div{display:flex;flex-direction:column}.bp-stats>div+div{padding-left:22px;border-left:1px solid var(--bp-border)}.bp-stats span{color:var(--bp-muted);font-size:12px;font-weight:600}.bp-stats strong{font-size:24px;line-height:1.35;font-weight:700;letter-spacing:-.7px;margin:3px 0 2px;font-variant-numeric:tabular-nums;white-space:nowrap;color:#0f172a}.bp-stats em{font-size:14px;font-style:normal;font-weight:500;letter-spacing:0;color:var(--bp-muted)}.bp-stats small{font-size:11px;color:var(--bp-muted)}.bp-status-value[data-status=passed]{color:var(--bp-green)}.bp-status-value[data-status=running]{color:var(--bp-blue)}.bp-status-value[data-status=failed],.bp-status-value[data-status=canceled]{color:var(--bp-red)}
.bp-context{display:flex;justify-content:space-between;align-items:center;gap:8px;margin:0 28px 0;padding-top:14px;border-top:1px solid var(--bp-border);font-size:11px;color:var(--bp-muted)}.bp-context>span,.bp-context>div{display:flex;align-items:center;gap:6px;min-width:0;flex-wrap:wrap}.bp-context code{font-family:ui-monospace,SFMono-Regular,Consolas,monospace;font-size:11px;font-weight:600;color:#334155}.bp-dot{padding:0 2px}.bp-replay,.bp-cancel{display:flex;align-items:center;justify-content:center;gap:5px;border:1px solid var(--bp-border);border-radius:8px;min-height:30px;padding:0 10px;font-size:11px!important;font-weight:600;background:rgba(255,255,255,0.9);box-shadow:0 1px 3px rgba(0,0,0,0.03)}.bp-replay:hover,.bp-cancel:hover{background:rgba(255,255,255,1);color:var(--bp-ink)}
.bp-plot{position:relative;margin:0 16px 0}.bp-chart{display:block}.bp-station-block{--bp-top:var(--bp-gray-fill)}.bp-station-block[data-status=passed]{--bp-top:var(--bp-green-fill)}.bp-station-block[data-status=running]{--bp-top:var(--bp-blue-fill)}.bp-station-block[data-status=failed],.bp-station-block[data-status=canceled]{--bp-top:var(--bp-red-fill)}.bp-roof{fill:var(--bp-top)}.bp-left{fill:color-mix(in srgb,var(--bp-top) 89%,var(--bp-ink) 11%)}.bp-right{fill:color-mix(in srgb,var(--bp-top) 75%,var(--bp-ink) 25%)}.bp-station-block polygon{transition:fill .3s ease}.bp-station-button{position:absolute;width:108px;height:104px;border:0;padding:0;background:transparent;text-align:center;display:flex;align-items:center;flex-direction:column;border-radius:10px}.bp-station-icon{height:40px;display:flex;align-items:center;justify-content:center;transition:transform .18s ease;color:var(--bp-muted)}.bp-station-button[data-status=passed] .bp-station-icon{color:var(--bp-green)}.bp-station-button[data-status=running] .bp-station-icon{color:var(--bp-blue)}.bp-station-button[data-status=failed] .bp-station-icon{color:var(--bp-red)}.bp-station-button:hover .bp-station-icon{transform:translateY(-2px)}.bp-station-button>strong{font-size:12px;font-weight:700;margin-top:23px;line-height:18px;max-width:104px;overflow-wrap:anywhere;color:#0f172a}.bp-station-state{display:flex;align-items:center;justify-content:center;gap:4px;color:var(--bp-muted);font-size:11px;font-weight:500;line-height:18px;flex-wrap:wrap}.bp-station-state>svg{color:inherit}.bp-station-button[data-status=passed] .bp-station-state>svg{color:var(--bp-green)}.bp-station-button[data-status=failed] .bp-station-state>svg{color:var(--bp-red)}.bp-station-duration{font-variant-numeric:tabular-nums;margin-left:2px}
.bp-list{padding:12px 28px 20px}.bp-list-row{display:flex;align-items:center;gap:12px;min-height:56px;padding:10px 12px;width:100%;text-align:left;background:transparent;border:0;border-radius:12px;min-width:0;transition:all .15s ease}.bp-list-row+.bp-list-row{border-top:1px solid var(--bp-border)}.bp-list-row[aria-pressed=true]{background:rgba(255,255,255,0.9);box-shadow:0 2px 8px rgba(0,0,0,0.04)}.bp-list-row:hover{background:rgba(255,255,255,0.7)}.bp-list-row>svg{color:var(--bp-muted)}.bp-list-row>span:nth-child(2){flex:1;min-width:0}.bp-list-row strong{display:block;font-size:13px;font-weight:700;overflow-wrap:anywhere;color:#0f172a}.bp-list-row small{display:block;color:var(--bp-muted);font-size:11px}.bp-list-status{display:flex;align-items:center;gap:5px;font-size:11px;font-weight:600;white-space:nowrap}.bp-list-duration{font-size:11px;color:var(--bp-muted);min-width:35px;text-align:right;font-variant-numeric:tabular-nums}.bp-list-row[data-status=passed] .bp-list-status{color:var(--bp-green)}.bp-list-row[data-status=running] .bp-list-status{color:var(--bp-blue)}.bp-list-row[data-status=failed] .bp-list-status{color:var(--bp-red)}
.bp-log-panel{margin:0 28px;border:1px solid var(--bp-border);border-radius:14px;background:rgba(248,250,252,0.85);backdrop-filter:blur(8px);overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.02)}.bp-log-header{display:flex;justify-content:space-between;align-items:center;gap:8px;padding:10px 14px;border-bottom:1px solid var(--bp-border);flex-wrap:wrap}.bp-log-header>div{display:flex;align-items:center;gap:8px;min-width:0}.bp-log-header strong{font-weight:700;font-size:13px;overflow-wrap:anywhere;color:#0f172a}.bp-stage-badge{font-size:11px;font-weight:600;color:var(--bp-muted)}.bp-stage-badge[data-status=passed]{color:var(--bp-green)}.bp-stage-badge[data-status=running]{color:var(--bp-blue)}.bp-stage-badge[data-status=failed]{color:var(--bp-red)}.bp-log-filter{display:flex;align-items:center;position:relative}.bp-log-filter select{appearance:none;background:rgba(255,255,255,0.9);border:1px solid var(--bp-border);border-radius:7px;font-size:11px;font-weight:600;height:28px;padding:0 24px 0 9px}.bp-log-filter>svg{position:absolute;right:8px;pointer-events:none;color:var(--bp-muted)}.bp-export{display:grid;place-items:center;width:28px;height:28px;padding:0;border:0;background:transparent;border-radius:7px}.bp-export:hover:not(:disabled){background:rgba(255,255,255,0.9)}.bp-log-lines{padding:12px 14px}.bp-log-line{display:flex;gap:10px;padding:3px 0;font-size:11px;line-height:1.6}.bp-log-line time{color:var(--bp-muted);font-family:ui-monospace,SFMono-Regular,Consolas,monospace;font-variant-numeric:tabular-nums;flex:none}.bp-log-line code{font-family:ui-monospace,SFMono-Regular,Consolas,monospace;font-size:11px;overflow-wrap:anywhere;white-space:pre-wrap;min-width:0;color:#1e293b}.bp-log-line[data-level=error] code{color:var(--bp-red)}.bp-no-logs{margin:2px 0;color:var(--bp-muted);font-size:11px}.bp-full-logs{padding:0 14px 12px}.bp-full-logs summary{display:flex;align-items:center;justify-content:space-between;list-style:none;min-height:30px;color:var(--bp-muted);font-size:11px;cursor:pointer}.bp-full-logs summary::-webkit-details-marker{display:none}.bp-full-logs summary:hover{color:var(--bp-ink)}.bp-full-logs[open] summary>svg{transform:rotate(180deg)}.bp-footer{display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:6px;margin:16px 28px 22px;font-size:11px;color:var(--bp-muted);font-weight:500}.bp-footer>span:first-child{display:flex;align-items:center;gap:5px}.bp-empty{display:flex;align-items:center;justify-content:center;flex-direction:column;gap:9px;min-height:190px;color:var(--bp-muted);padding:24px 18px}.bp-empty strong{font-size:13px;font-weight:700;color:var(--bp-ink)}.bp-empty p{font-size:12px;margin:0}
@media(max-width:560px){.bp-header{padding:19px 18px 0;flex-wrap:wrap;gap:14px}.bp-header-tools{width:100%;justify-content:space-between}.bp-run-select{flex:1;max-width:230px}.bp-run-select select{width:100%;max-width:none}.bp-stats{margin:22px 18px 18px;gap:8px}.bp-stats>div+div{padding-left:12px}.bp-stats span{font-size:11px}.bp-stats strong{font-size:21px}.bp-context{margin-inline:18px;flex-wrap:wrap}.bp-list{padding-inline:18px}.bp-log-panel{margin-inline:18px}.bp-footer{margin-inline:18px}.bp-log-line{gap:7px}}
@media(max-width:380px){.bp-stats strong{font-size:19px}.bp-stats em{font-size:12px}.bp-list-row{gap:7px}.bp-list-duration{min-width:28px}.bp-log-header>div:last-child{width:100%;justify-content:space-between}.bp-context>div{margin-left:auto}.bp-log-line{flex-wrap:wrap}.bp-log-line code{width:100%}}
@media(pointer:coarse){.bp-switch button{height:38px;min-width:44px}.bp-run-select select{height:44px;font-size:16px}.bp-replay,.bp-cancel{min-height:44px;min-width:44px}.bp-log-filter select{height:44px;font-size:16px;max-width:230px}.bp-export{height:44px;width:44px}.bp-full-logs summary{min-height:44px}}
@media(prefers-reduced-motion:reduce){.build-pipeline *{transition:none!important;animation:none!important}}
`;
