-- ============================================================================
-- DOCKPROOF AI WAREHOUSE RECEIVING MANAGER: STORAGE BUCKETS & POLICIES
-- Migration: 20260930000003_storage_buckets_and_policies.sql
-- Description: Creates private buckets and strict access policies
-- ============================================================================

-- 1. Create Private Buckets
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES 
  ('inspection-evidence', 'inspection-evidence', false, 52428800, ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/heic']),
  ('inspection-analysis', 'inspection-analysis', false, 20971520, ARRAY['image/jpeg', 'image/png', 'image/webp']),
  ('product-reference-images', 'product-reference-images', false, 10485760, ARRAY['image/jpeg', 'image/png', 'image/webp'])
ON CONFLICT (id) DO UPDATE SET
  public = EXCLUDED.public,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

-- ============================================================================
-- STORAGE RLS POLICIES FOR storage.objects
-- ============================================================================

-- Enable RLS on storage.objects if not already enabled
ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;

-- ----------------------------------------------------------------------------
-- BUCKET 1: inspection-evidence (Original Immutable Photos)
-- ----------------------------------------------------------------------------

-- Operators and Managers can read evidence photos for inspections they have access to
CREATE POLICY "evidence_select_policy"
  ON storage.objects FOR SELECT
  TO authenticated
  USING (
    bucket_id = 'inspection-evidence'
    AND (
      is_manager()
      OR is_service_role()
      OR EXISTS (
        SELECT 1 FROM inspections
        WHERE inspections.id::text = (storage.foldername(name))[1]
        AND inspections.operator_id = auth.uid()
      )
    )
  );

-- Operators can upload photos only to inspections they own and which are IN_PROGRESS
CREATE POLICY "evidence_insert_operator"
  ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (
    bucket_id = 'inspection-evidence'
    AND (
      is_manager()
      OR is_service_role()
      OR EXISTS (
        SELECT 1 FROM inspections
        WHERE inspections.id::text = (storage.foldername(name))[1]
        AND inspections.operator_id = auth.uid()
        AND inspections.status = 'IN_PROGRESS'
      )
    )
  );

-- IMMUTABILITY ENFORCEMENT: Overwriting existing evidence files is strictly denied
CREATE POLICY "evidence_no_update"
  ON storage.objects FOR UPDATE
  TO authenticated
  USING (false);

-- IMMUTABILITY ENFORCEMENT: Deleting evidence files is strictly denied for operators
CREATE POLICY "evidence_no_delete_operators"
  ON storage.objects FOR DELETE
  TO authenticated
  USING (is_service_role());

-- ----------------------------------------------------------------------------
-- BUCKET 2: inspection-analysis (Compressed AI copies generated by Edge Functions)
-- ----------------------------------------------------------------------------

-- Readable by authenticated users with inspection access
CREATE POLICY "analysis_select_policy"
  ON storage.objects FOR SELECT
  TO authenticated
  USING (
    bucket_id = 'inspection-analysis'
    AND (
      is_manager()
      OR is_service_role()
      OR EXISTS (
        SELECT 1 FROM inspections
        WHERE inspections.id::text = (storage.foldername(name))[1]
        AND inspections.operator_id = auth.uid()
      )
    )
  );

-- Only service role (Edge Functions) can write analysis artifacts
CREATE POLICY "analysis_insert_service_role"
  ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (
    bucket_id = 'inspection-analysis'
    AND is_service_role()
  );

CREATE POLICY "analysis_no_update"
  ON storage.objects FOR UPDATE
  TO authenticated
  USING (is_service_role());

CREATE POLICY "analysis_no_delete"
  ON storage.objects FOR DELETE
  TO authenticated
  USING (is_service_role());

-- ----------------------------------------------------------------------------
-- BUCKET 3: product-reference-images (Catalogue reference imagery)
-- ----------------------------------------------------------------------------

-- Any authenticated user (operator or manager) can read product reference photos
CREATE POLICY "product_ref_select_authenticated"
  ON storage.objects FOR SELECT
  TO authenticated
  USING (bucket_id = 'product-reference-images');

-- Only managers or service role can upload or modify product reference photos
CREATE POLICY "product_ref_insert_manager"
  ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (
    bucket_id = 'product-reference-images'
    AND (is_manager() OR is_service_role())
  );

CREATE POLICY "product_ref_update_manager"
  ON storage.objects FOR UPDATE
  TO authenticated
  USING (
    bucket_id = 'product-reference-images'
    AND (is_manager() OR is_service_role())
  );

CREATE POLICY "product_ref_delete_manager"
  ON storage.objects FOR DELETE
  TO authenticated
  USING (
    bucket_id = 'product-reference-images'
    AND (is_manager() OR is_service_role())
  );
